const $=id=>document.getElementById(id);const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=ms=>ms?new Date(ms).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
async function api(path){const r=await fetch(path,{headers:{accept:'application/json'}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Request failed (${r.status})`);return body}
function showError(error){$('error').textContent=error.message||String(error);$('error').classList.remove('hidden')}
function clearError(){$('error').classList.add('hidden')}
function renderMembers(members){$('member-results').innerHTML=members.length?members.map(m=>`<div class="result" data-member="${esc(m.id)}"><strong>${esc(m.callsign||'No callsign')} · ${esc(m.displayName)}</strong><div class="result-meta"><span>Rank: <b>${esc(m.rank||'Unassigned')}</b></span><span>Status: ${esc(m.status)}</span><span>${esc(m.discordId)}</span></div></div>`).join(''):'<p class="muted">No matching personnel found.</p>';document.querySelectorAll('[data-member]').forEach(el=>el.addEventListener('click',()=>loadTimeline(el.dataset.member)))}
async function searchMembers(){clearError();try{const data=await api(`/api/members?q=${encodeURIComponent($('member-search').value)}`);renderMembers(data.members)}catch(error){showError(error)}}
async function loadTimeline(id){clearError();try{const data=await api(`/api/members/${encodeURIComponent(id)}`);$('timeline-panel').classList.remove('hidden');$('timeline-title').textContent=`${data.member.callsign||'Member'} · ${data.member.displayName}`;$('timeline').innerHTML=data.timeline.length?data.timeline.map(item=>`<div class="timeline-item"><div class="timeline-date">${esc(item.effectiveDate||fmt(item.createdAt))}</div><div><div class="timeline-type">${esc(item.recordType)} <span class="pill">${esc(item.status)}</span></div><div class="timeline-detail">${esc(Object.values(item.data||{}).filter(Boolean).slice(0,4).join(' · ')||'Structured RMS record')}</div></div></div>`).join(''):'<p class="muted">No finalized RMS records yet.</p>';$('timeline-panel').scrollIntoView({behavior:'smooth',block:'start'})}catch(error){showError(error)}}
async function loadApprovals(){try{const data=await api('/api/approvals');$('approval-count').textContent=data.approvals.length;$('approval-results').innerHTML=data.approvals.length?data.approvals.map(a=>`<div class="approval"><strong>${esc(a.workflowType)} · ${esc(a.stage)}</strong><small>Requested by ${esc(a.requestedBy)} · ${fmt(a.requestedAt)}</small><small>${a.expiresAt?`Expires ${fmt(a.expiresAt)}`:'No expiry configured'}</small></div>`).join(''):'<p class="muted">No pending approvals.</p>'}catch(error){$('approval-results').innerHTML='<p class="muted">Approval queue unavailable for this account.</p>'}}
async function loadAudit(){try{const data=await api('/api/audit');$('audit-panel').classList.remove('hidden');$('audit-results').innerHTML=data.events.map(e=>`<div class="audit-row"><span>${esc(fmt(e.createdAt))}</span><span><strong>${esc(e.action)}</strong><small>${esc(e.entityType)} ${esc(e.entityId||'')}</small></span><span>${esc(e.actorDiscordId||'system')}</span></div>`).join('')||'<p class="muted">No audit activity yet.</p>'}catch(error){showError(error)}}
async function boot(){try{const data=await api('/api/me');$('signed-out').classList.add('hidden');$('app').classList.remove('hidden');$('identity').innerHTML=`<span class="identity-name">${esc(data.member?.displayName||data.account.discordId)}</span><a class="button ghost" href="/auth/logout">Sign out</a>`;$('welcome-title').textContent=`Welcome, ${data.member?.displayName||'RMS user'}.`;$('access-pill').textContent=data.account.accessLevel;$('welcome-subtitle').textContent='Your RMS views and actions are recorded in the audit trail.';if(['pab','command','admin'].includes(data.account.accessLevel)){await searchMembers();await loadApprovals()}if(['command','admin'].includes(data.account.accessLevel))await loadAudit()}catch(error){if(!/Sign in/.test(error.message))showError(error)}}
let timer; $('member-search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(searchMembers,250)});$('refresh-approvals').addEventListener('click',loadApprovals);$('refresh-audit').addEventListener('click',loadAudit);$('close-timeline').addEventListener('click',()=>$('timeline-panel').classList.add('hidden'));boot();
